List<List<dynamic>> kCategoryList = [
  [
    "New",
    [
       "assets/images/NewCategory.png",
       "assets/images/men_new.png",
       "assets/images/kids_new.jpg"
    ]
  ],
  [
    "Clothes",
    [
       "assets/images/Clothes.png",
      "assets/images/mens_clothes.jpg",
      "assets/images/kids_clothes.jpg"
    ]
  ],
  [
    "Shoes",
    [
       "assets/images/Shoes.png",
       "assets/images/mens_shoes.png",
      "assets/images/kids_shoes.png"
    ]
  ],
  [
    "Accesories",
    [
      "assets/images/Accesories.png",
     "assets/images/mens_acc.jpg",
     "assets/images/kids_acc.jpg"
    ]
  ],
];
List<String> kTypes = ['Women', 'Men', 'Kids'];
